pref("extensions.nosquint.zoomlevel", 120);
pref("extensions.nosquint.zoomIncrement", 10);
pref("extensions.nosquint.rememberSites", true);
pref("extensions.nosquint.sites", "");
pref("extensions.nosquint.sitesSaveDelay", 5000);
pref("extensions.nosquint.exceptions", "*/~* *.sourceforge.net *.google.[*]");
pref("extensions.nosquint.wheelZoomEnabled", false);
pref("extensions.nosquint.hideStatus", false);
pref("extensions.nosquint.forgetMonths", 6);
pref("extensions.nosquint.fullZoomPrimary", true);
